### ISSUE TITLE
(node:14696) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot set property 'userId' of undefined

### ISSUE THREAD

**Issue by iDamira** [iDamira/Cat_links#1]
@trevorpreston
@gittheking
@jasonseminara
@rapala61
@irwintsay
@nickykwan

<img width="1035" alt="screen shot 2016-10-31 at 1 55 52 pm" src="https://cloud.githubusercontent.com/assets/19273883/19865339/33ccbe42-9f72-11e6-8da5-a15c2b74d812.png">

Snippet:
<img width="544" alt="screen shot 2016-10-31 at 2 01 28 pm" src="https://cloud.githubusercontent.com/assets/19273883/19865443/9e22b36e-9f72-11e6-970c-ca1558c415c9.png">

Error message:
(node:14696) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot set property 'userId' of undefined -- looks like my session isn't working?

Tell us 3 things that you tried in order to solve the issue:
1. Copied code from crud iTunes auth
2. Consulted with groupmates, they all have same code and their code works
3. Restarted computer))

**Comment by trevorpreston** [comment]
Not queued yet.  Waiting for more information.
